[build-system]
requires = ["poetry-core>=2.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name = "django-new-forms"
description = "Django forms validation using external serializers"
version = "0.1.0"
license = "MIT"
requires-poetry = ">=2.2"

authors = [
  "Nikita Sobolev <mail@sobolevn.me>",
  "Alexander Kondratev <mail@kondratev.dev>",
]

readme = "README.md"

repository = "https://github.com/wemake-services/django-new-forms"

keywords = [
  "django",
  "django plugin",
  "forms",
  "pydantic",
  "msgspec",
  "wemake-python-package",
]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Environment :: Web Environment",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Framework :: Django",
  "Framework :: Django :: 4.2",
  "Framework :: Django :: 5.0",
  "Framework :: Django :: 5.1",
  "Framework :: Django :: 5.2",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]


[tool.poetry.dependencies]
python = ">=3.12,<3.15"
typing_extensions = ">=4.0"
django = ">=5.0,<6.2"

msgspec = { version = ">= 0.19", optional = true }
pydantic = { version = "^2.12", optional = true }

[tool.poetry.extras]
pydantic = ["pydantic"]
msgspec = ["msgspec"]

[tool.poetry.group.dev.dependencies]
django = "^6.1"
django-stubs = { version = "^6.1", extras = ["compatible-mypy"] }
django-stubs-ext = "^6.1"

pyright = "^1.1"
mypy = "^2.3"

wemake-python-styleguide = "^1.4"
ruff = "^0.16"

pytest = "^9.0"
pytest-cov = "^7.0"
pytest-django = "^4.11"
pytest-randomly = "^5.0"

codespell = "^2.4"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "^8.1"
sphinx-autodoc-typehints = "^3.0"
tomli = "^2.3"
myst-parser = ">=4,<6"
furo = "^2025.9"


[tool.ruff]
# Ruff config: https://docs.astral.sh/ruff/settings
preview = true
fix = true
target-version = "py311"
line-length = 80

[tool.ruff.format]
quote-style = "single"
docstring-code-format = true

[tool.ruff.lint]
select = [
  "A",     # flake8-builtins
  "ASYNC", # flake8-async
  "B",     # flake8-bugbear
  "C4",    # flake8-comprehensions
  "C90",   # mccabe
  "COM",   # flake8-commas
  "D",     # pydocstyle
  "DJ",    # flake8-django
  "DTZ",   # flake8-datetimez
  "E",     # pycodestyle
  "ERA",   # flake8-eradicate
  "EXE",   # flake8-executable
  "F",     # pyflakes
  "FBT",   # flake8-boolean-trap
  "FLY",   # pyflint
  "FURB",  # refurb
  "G",     # flake8-logging-format
  "I",     # isort
  "ICN",   # flake8-import-conventions
  "INT",   # flake8-gettext
  "ISC",   # flake8-implicit-str-concat
  "LOG",   # flake8-logging
  "N",     # pep8-naming
  "PERF",  # perflint
  "PIE",   # flake8-pie
  "PL",    # pylint
  "PT",    # flake8-pytest-style
  "PTH",   # flake8-use-pathlib
  "Q",     # flake8-quotes
  "RET",   # flake8-return
  "RSE",   # flake8-raise
  "RUF",   # ruff
  "S",     # flake8-bandit
  "SIM",   # flake8-simplify
  "SLF",   # flake8-self
  "SLOT",  # flake8-slots
  "T100",  # flake8-debugger
  "TID",   # flake8-tidy-imports
  "TRY",   # tryceratops
  "UP",    # pyupgrade
  "W",     # pycodestyle
  "YTT",   # flake8-2020
]
ignore = [
  "A005",     # allow to shadow stdlib and builtin module names
  "ASYNC119", # `contextlib.aclosing` is not detected
  # Different doc rules that we don't really care about:
  "D100",
  "D104",
  "D106",
  "D203",
  "D212",
  "D401",
  "D404",
  "D405",
  "D418",     # We should be able to add docstrings to `@overload` decorators
  "D421",
  "DJ008",    # we don't need `__str__` in models in tests
  "ISC001",   # implicit string concat conflicts with `ruff format`
  "ISC003",   # prefer explicit string concat over implicit concat
  "PLC0414",  # do not raise on `as` re-exports
  "PLR09",    # we have our own complexity rules
  "PLR2004",  # do not report magic numbers
  "PLR6301",  # do not require classmethod / staticmethod when self not used
  "PLW2901",  # allow to redefine iteration targets in for loops
  "RUF029",   # we decide `async` functions based on API, not `await` usage
  "RUF067",   # wps handles `__init__.py` logic better
  "RUF105",   # keep old `# noqa` comments style, not `# ruff` comments
  "RUF106",   # we prefer old error codes
  "RUF201",   # keep old rule codes instead of verbose names
  "TRY003",   # long exception messages from `tryceratops`
]
external = [ "WPS" ]

# Plugin configs:
flake8-quotes.inline-quotes = "single"
mccabe.max-complexity = 6
pydocstyle.convention = "google"

# For `django_test_app` only:
isort.known-first-party = ["new_forms"]

[tool.ruff.lint.per-file-ignores]
# Allow public re-exports:
"django_new_forms/serializers/__init__.py" = ["useless-import-alias"]
# Allow `assert`s in tests:
"tests/*.py" = ["assert"]


[tool.pytest.ini_options]
# Django options:
# https://pytest-django.readthedocs.io/en/latest/
DJANGO_SETTINGS_MODULE = "server.settings"

# pytest config: http://doc.pytest.org/en/latest/customize.html
# Strict `@xfail` by default:
xfail_strict = true
# Fail on warnings:
filterwarnings = ["error"]

# PYTHONPATH configuration:
pythonpath = ["django_test_app"]

addopts = [
  "--strict-config",
  "--strict-markers",
  "--doctest-modules",
    # Output:
  "--tb=short",
  # Coverage:
  "--cov=django_new_forms",
  "--cov-report=term-missing:skip-covered",
  "--cov-report=html",
  "--cov-report=xml",
  "--cov-branch",
  "--cov-fail-under=64",
  # Ignores:
  "--ignore=docs",
]


[tool.mypy]
# The mypy configurations: http://bit.ly/2zEl9WI
extra_checks = true
strict_equality_for_none = true
strict = true

enable_error_code = [
  "deprecated",
  "exhaustive-match",
  "explicit-override",
  "ignore-without-code",
  "possibly-undefined",
  "redundant-expr",
  "redundant-self",
  "truthy-bool",
  "truthy-iterable",
  "unimported-reveal",
  "unused-awaitable",
]

plugins = [
  "pydantic.mypy",
]

[tool.pyright]
# Docs: https://microsoft.github.io/pyright/#/configuration
include = ["django_new_forms", "tests"]
strict = ["django_new_forms/**/*"]
venvPath = "."
venv = ".venv"



[tool.codespell]
# codespell configuration: https://github.com/codespell-project/codespell
skip = [
  "*.css",
  "*.js",
  "*.lock",
  "*.min.*",
  "*.msgpack",
  ".mypy_cache",
  "__pycache__",
  "_build",
]
